.TH TG 1
.SH NAME
tg \- a program for timing mechanincal watches
.SH SYNOPSIS
.nf
.B tg-timer
.fi
.SH DESCRIPTION
Tg (tg-timer) is a program to evaluate the performance of mechanical watch
movements. Tg works with the noise produced by a watch mechanism, and it
produces real-time readings of the rate (or accuracy) and various other
operational parameters. 
